### ISSUE TITLE
Exceptions insideCommand parsing results in CommandTimeout instead of imediate failure

### ISSUE THREAD

**Issue by greg-latuszek** [nokia/moler#14]
Correct coding style for writing Commands is to use `self.set_exception(Err)` when you want to signal some error during parsing or if you detect command failure.

But that assumes:

1. that we have well trained Command developer knowing that convention
2. that nothing raises unexpected exception inside code used for parsing - such code may use 3rd party libraries and who reads them against all possible exceptions?

**What will happen if above assumptions are not true?**

I have made experiment. Modified https://github.com/nokia/moler/blob/b7af9e41dc2d15af944e53c2a92969395ae9f140/moler/cmd/unix/chown.py#L43 as follows:

```
    def _parse_error(self, line):
        raise Exception("Broken parsing inside on_new_line")
        if self._regex_helper.search(Chown._reg_fail, line):
            self.set_exception(CommandFailure(self, "ERROR: {}or {}".format(self._regex_helper.group("ERROR"),
                                                                            self._regex_helper.group("ERROR1"))))
            raise ParsingDone
```

result during tests is:
```
>           raise CommandTimeout(connection_observer, timeout, kind="await_done", passed_time=passed)
E           moler.exceptions.CommandTimeout: Chown("chown   /rom/swconfig.txt", id:7f01984f0128) await_done time 7.06 >= 7.00 sec timeout

../moler/runner.py:160: CommandTimeout
```
but real cause is that we have unhandled exception causing thread of connection to die:
```
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/opt/ute/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/ute/python3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ute/auto/moler/moler/moler/io/raw/memory.py", line 252, in pull_data
    self.read()  # internally forwards to embedded Moler connection
  File "/home/ute/auto/moler/moler/moler/io/raw/memory.py", line 176, in read
    self.data_received(data)
  File "/home/ute/auto/moler/moler/moler/io/io_connection.py", line 102, in data_received
    self.moler_connection.data_received(data)
  File "/home/ute/auto/moler/moler/moler/connection.py", line 195, in data_received
    self.notify_observers(decoded_data)
  File "/home/ute/auto/moler/moler/moler/connection.py", line 233, in notify_observers
    observer_function(observer_self, data)
  File "/home/ute/auto/moler/moler/moler/cmd/commandtextualgeneric.py", line 95, in data_received
    self.on_new_line(line, is_full_line)
  File "/home/ute/auto/moler/moler/moler/cmd/unix/chown.py", line 33, in on_new_line
    self._parse_error(line)
  File "/home/ute/auto/moler/moler/moler/cmd/unix/chown.py", line 44, in _parse_error
    raise Exception("Broken parsing inside on_new_line")
Exception: Broken parsing inside on_new_line
```
**This has very negative impact**:

- even best connection may be totally broken by single command !!!
- command failure is detected after its timeout instead of "immediately"

**Moler should be secured for such cases. It should take over such Exception and redirect it to `self.set_exception()` of command/connection_observer**

**Comment by emcek** [comment]
@greg-latuszek this is still valid issue?

**Comment by greg-latuszek** [comment]
It is already solved
