### ISSUE TITLE
Print stack traceback on demand

### ISSUE THREAD

**Issue by lukiii** [nokia/moler#157]
On terminal appears stack  traceback after unsuccessful connection with device , even after correct handling of exception:

Device 'xxx' failed with 'Exception raised by device 'xxx' SM when try to changing state: 'Traceback (most recent call last):
  File "/opt/ute/python/lib/python2.7/site-packages/moler/device/textualdevice.py", line 247, in _trigger_change_state
    change_state_method(self.current_state, next_state, timeout=timeout)
  File "/opt/ute/python/lib/python2.7/site-packages/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/opt/ute/python/lib/python2.7/site-packages/transitions/core.py", line 1059, in _process
    self._transition_queue[0]()
  File "/opt/ute/python/lib/python2.7/site-packages/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/opt/ute/python/lib/python2.7/site-packages/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/opt/ute/python/lib/python2.7/site-packages/transitions/core.py", line 250, in execute
    machine.callback(func, event_data)
  File "/opt/ute/python/lib/python2.7/site-packages/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/opt/ute/python/lib/python2.7/site-packages/moler/device/unixlocal.py", line 161, in _execute_command_to_change_state
    command(timeout=command_timeout)
  File "/opt/ute/python/lib/python2.7/site-packages/moler/connection_observer.py", line 92, in __call__
    return self.await_done()
  File "/opt/ute/python/lib/python2.7/site-packages/moler/connection_observer.py", line 216, in await_done
    return self.result()
  File "/opt/ute/python/lib/python2.7/site-packages/moler/connection_observer.py", line 300, in result
    raise exception
CommandTimeout: Ssh("TERM=xterm-mono ssh -p 22 -l UUU YYY", id:7fc76c3c4a10) background_run time 7.00 >= 7.00 sec timeout

Moler should print stack traceback on demand?

**Comment by marcin-usielski** [comment]
Added parameter log_stacktrace_on_fail=True to goto_state method for devices.
